const fs = require('fs');
const path = require('path');

const filePath = path.resolve('c:/Users/admin/Desktop/visual-CN-arch-main/src/pages/TimelinePage.tsx');
let content = fs.readFileSync(filePath, 'utf8');

if (content.includes("id: 499, name: '漳州东山关帝庙'")) {
  console.log('Part2 already applied.');
  process.exit(0);
}

const moreBuildings = `
    { id: 400, name: '安岳毗卢洞石刻', year: 907, dynasty: '五代', desc: '川中石刻艺术代表，造像精美', tech: '石窟艺术·密宗题材', category: '石窟', impactFactor: 7, features: { structureType: '石构', roofType: '无', material: ['石'], constructionTech: ['石刻', '摩崖'] } },
    { id: 401, name: '乐山乌尤寺', year: 742, dynasty: '唐', desc: '凌云山寺院群的一部分，与大佛景观相伴', tech: '山地寺庙·江岸格局', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '石'], constructionTech: ['依山而建', '榫卯'] } },
    { id: 402, name: '峨眉山万年寺无梁砖殿', year: 1600, dynasty: '明', desc: '砖石拱券技术建成的佛殿，结构特殊', tech: '无梁砖殿·拱券结构', category: '寺庙', impactFactor: 8, features: { structureType: '砖石', roofType: '拱顶', material: ['砖'], constructionTech: ['拱券', '无梁结构'] } },
    { id: 403, name: '阆中古城华光楼', year: 1370, dynasty: '明', desc: '阆中古城标志性楼阁，嘉陵江景观节点', tech: '古城楼阁·临江构景', category: '楼阁', impactFactor: 7, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['榫卯', '楼阁结构'] } },
    { id: 404, name: '三苏祠飨殿', year: 1300, dynasty: '元', desc: '纪念苏洵苏轼苏辙的祠园建筑群核心', tech: '祠园建筑·文脉传承', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['院落布局', '榫卯'] } },
    { id: 405, name: '雅安上里韩家大院', year: 1800, dynasty: '清', desc: '川西传统民居，兼有院落与商业空间', tech: '川西民居·木石结合', category: '民居', impactFactor: 5, features: { structureType: '木石', roofType: '悬山顶', material: ['木', '石'], constructionTech: ['穿斗式', '院落布局'] } },
    { id: 406, name: '宜宾真武山古建筑群', year: 1500, dynasty: '明', desc: '川南道教与寺庙建筑群，山地布局明显', tech: '山地古建群·真武信仰', category: '道观', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '石'], constructionTech: ['依山而建', '榫卯'] } },
    { id: 407, name: '昆明金殿', year: 1602, dynasty: '明', desc: '中国现存最大铜殿，金属构件建筑罕见', tech: '铜殿·金属构造', category: '道观', impactFactor: 8, features: { structureType: '金属', roofType: '歇山顶', material: ['铜'], constructionTech: ['金属铸造', '榫接'] } },
    { id: 408, name: '昆明圆通寺', year: 765, dynasty: '唐', desc: '云南著名古寺，地势下沉式布局独特', tech: '唐代古寺·下沉院落', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '石'], constructionTech: ['院落布局', '榫卯'] } },
    { id: 409, name: '大理弘圣寺塔', year: 877, dynasty: '南诏', desc: '大理地区著名古塔，南诏佛教建筑代表', tech: '南诏古塔·密檐塔', category: '塔', impactFactor: 7, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['密檐塔', '砖砌'] } },
    { id: 410, name: '巍山文庙大成殿', year: 1410, dynasty: '明', desc: '云南文庙建筑代表，地方礼制建筑保存较好', tech: '明代文庙·边疆礼制', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 411, name: '建水朝阳楼', year: 1389, dynasty: '明', desc: '滇南古城标志性城楼，尺度宏大', tech: '明代城楼·滇南重镇', category: '城防', impactFactor: 7, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['城楼结构', '榫卯'] } },
    { id: 412, name: '建水双龙桥', year: 1795, dynasty: '清', desc: '云南大型多孔石拱桥，桥亭结合鲜明', tech: '多孔石桥·桥亭组合', category: '桥梁', impactFactor: 7, features: { structureType: '砖石', roofType: '亭顶', material: ['石'], constructionTech: ['石拱', '桥亭结合'] } },
    { id: 413, name: '石屏文庙', year: 1285, dynasty: '元', desc: '西南地区保存较完整的文庙建筑群', tech: '元代文庙·礼制建筑', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['院落布局', '榫卯'] } },
    { id: 414, name: '丽江木府议事厅', year: 1600, dynasty: '明', desc: '纳西土司官署建筑群核心空间', tech: '土司官署·纳西木构', category: '宫殿', impactFactor: 7, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['榫卯', '院落布局'] } },
    { id: 415, name: '丽江黑龙潭得月楼', year: 1737, dynasty: '清', desc: '玉龙雪山倒影景观中的楼阁建筑', tech: '园林楼阁·借景雪山', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '攒尖顶', material: ['木', '石'], constructionTech: ['借景', '榫卯'] } },
    { id: 416, name: '大理喜洲严家大院', year: 1907, dynasty: '清', desc: '白族民居代表，三坊一照壁格局鲜明', tech: '白族民居·三坊一照壁', category: '民居', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖', '石'], constructionTech: ['院落布局', '雕刻'] } },
    { id: 417, name: '腾冲和顺图书馆', year: 1928, dynasty: '民国', desc: '侨乡公共建筑代表，融合传统与近代空间形制', tech: '近代公共建筑·侨乡风格', category: '楼阁', impactFactor: 5, features: { structureType: '砖木', roofType: '歇山顶', material: ['砖', '木'], constructionTech: ['中西合璧'] } },
    { id: 418, name: '歙县许国石坊', year: 1584, dynasty: '明', desc: '明代著名石坊，牌坊建筑杰作', tech: '石坊·坊表制度', category: '祭祀', impactFactor: 7, features: { structureType: '石构', roofType: '牌坊顶', material: ['石'], constructionTech: ['石雕', '牌坊结构'] } },
    { id: 419, name: '歙县棠樾牌坊群', year: 1520, dynasty: '明', desc: '徽州牌坊群代表，集中体现宗法礼制', tech: '牌坊群·宗法礼制', category: '祭祀', impactFactor: 8, features: { structureType: '石构', roofType: '牌坊顶', material: ['石'], constructionTech: ['石雕', '坊表制度'] } },
    { id: 420, name: '黟县西递敬爱堂', year: 1680, dynasty: '清', desc: '徽州宗祠空间代表，木雕艺术突出', tech: '徽派宗祠·木雕', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['徽派木雕', '天井'] } },
    { id: 421, name: '黟县宏村南湖书院', year: 1814, dynasty: '清', desc: '徽派书院建筑，与水系村落空间一体化', tech: '徽派书院·水院结合', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖', '水'], constructionTech: ['天井', '借景'] } },
    { id: 422, name: '绩溪龙川胡氏宗祠', year: 1560, dynasty: '明', desc: '徽州宗祠代表，石雕木雕精美', tech: '宗祠建筑·徽派三雕', category: '祭祀', impactFactor: 8, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '石', '砖'], constructionTech: ['木雕', '砖雕', '石雕'] } },
    { id: 423, name: '休宁齐云山月华街古建筑群', year: 1400, dynasty: '明', desc: '道教名山街巷与宫观并存的山地聚落', tech: '山地道观·街庙结合', category: '道观', impactFactor: 6, features: { structureType: '木构', roofType: '悬山顶', material: ['木', '石'], constructionTech: ['依山而建', '街巷布局'] } },
    { id: 424, name: '寿县孔庙大成殿', year: 1312, dynasty: '元', desc: '安徽重要文庙建筑，保存元代形制特点', tech: '元代文庙·大成殿', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 425, name: '凤阳明中都皇城遗址', year: 1369, dynasty: '明', desc: '明代都城遗址，宫城格局规模宏大', tech: '都城遗址·皇城规划', category: '遗址', impactFactor: 8, features: { structureType: '土木', roofType: '无', material: ['砖', '土', '石'], constructionTech: ['夯土', '城址规划'] } },
    { id: 426, name: '天长护国寺塔', year: 1120, dynasty: '北宋', desc: '皖东古塔代表，砖构塔身保存较好', tech: '北宋砖塔·地方佛塔', category: '塔', impactFactor: 6, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['砖砌'] } },
    { id: 427, name: '亳州花戏楼', year: 1678, dynasty: '清', desc: '会馆戏楼建筑代表，木雕彩绘绚丽', tech: '戏楼建筑·彩绘木雕', category: '楼阁', impactFactor: 8, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['戏台结构', '木雕彩绘'] } },
    { id: 428, name: '安庆振风塔', year: 1570, dynasty: '明', desc: '长江沿岸地标古塔，七层八角', tech: '明代砖塔·江岸地标', category: '塔', impactFactor: 6, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['砖砌', '塔式结构'] } },
    { id: 429, name: '九江浔阳楼', year: 1574, dynasty: '明', desc: '临江楼阁，因文学叙事而闻名', tech: '临江楼阁·江城标识', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['榫卯', '楼阁结构'] } },
    { id: 430, name: '南昌佑民寺大雄宝殿', year: 1630, dynasty: '明', desc: '南昌著名佛寺核心建筑', tech: '明代寺院·大雄宝殿', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 431, name: '吉安白鹭洲书院', year: 1241, dynasty: '南宋', desc: '江西书院文化代表，洲岛空间布局独特', tech: '宋代书院·洲岛布局', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖', '水'], constructionTech: ['书院布局', '借景'] } },
    { id: 432, name: '庐山东林寺', year: 386, dynasty: '东晋', desc: '净土宗祖庭，佛教山林寺院代表', tech: '山林寺院·净土祖庭', category: '寺庙', impactFactor: 8, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '石'], constructionTech: ['依山而建', '榫卯'] } },
    { id: 433, name: '南丰曾巩读书岩', year: 1050, dynasty: '北宋', desc: '书院与摩崖环境相结合的文化遗存', tech: '书院遗迹·文人空间', category: '遗址', impactFactor: 5, features: { structureType: '石木', roofType: '无', material: ['石', '木'], constructionTech: ['摩崖', '园林布置'] } },
    { id: 434, name: '景德镇浮梁古县衙', year: 1280, dynasty: '元', desc: '保存较完整的古代县衙建筑群', tech: '衙署建筑·行政空间', category: '宫殿', impactFactor: 7, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['衙署布局', '榫卯'] } },
    { id: 435, name: '婺源汪口俞氏宗祠', year: 1736, dynasty: '清', desc: '徽派宗祠在赣东北的代表作品', tech: '宗祠建筑·徽派影响', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['木雕', '天井'] } },
    { id: 436, name: '龙虎山上清宫', year: 1060, dynasty: '北宋', desc: '正一道祖庭建筑群的重要组成', tech: '道教祖庭·宫观体系', category: '道观', impactFactor: 8, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '石'], constructionTech: ['榫卯', '宫观布局'] } },
    { id: 437, name: '抚州文昌里古建筑群', year: 1500, dynasty: '明', desc: '临川古城传统街巷与民居群代表', tech: '古街区·临川文脉', category: '民居', impactFactor: 5, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['街巷布局', '院落组合'] } },
    { id: 438, name: '武汉古琴台', year: 1473, dynasty: '明', desc: '纪念伯牙子期知音文化的古建园林', tech: '纪念园林·琴台建筑', category: '园林', impactFactor: 6, features: { structureType: '木构', roofType: '卷棚顶', material: ['木', '石', '水'], constructionTech: ['借景', '园林布局'] } },
    { id: 439, name: '武当山太和宫', year: 1416, dynasty: '明', desc: '武当山顶峰道教宫观，皇家敕建', tech: '明代道宫·高山宫殿', category: '道观', impactFactor: 9, features: { structureType: '木构', roofType: '重檐庑殿顶', material: ['木', '石', '铜'], constructionTech: ['依山而建', '榫卯', '皇家营造'] } },
    { id: 440, name: '武当山玉虚宫遗址', year: 1413, dynasty: '明', desc: '武当山山下最大道教宫殿遗址群', tech: '皇家道宫·遗址群', category: '遗址', impactFactor: 8, features: { structureType: '土木', roofType: '无', material: ['砖', '石', '土'], constructionTech: ['宫殿规划', '夯筑'] } },
    { id: 441, name: '襄阳古城昭明台', year: 1258, dynasty: '宋', desc: '襄阳古城高台楼阁，兼具历史纪念与瞭望功能', tech: '城内高台·楼阁纪念', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['楼阁结构', '高台建筑'] } },
    { id: 442, name: '荆州玄妙观三清殿', year: 1349, dynasty: '元', desc: '江汉平原道教建筑代表，木构价值突出', tech: '元代道观·三清殿', category: '道观', impactFactor: 8, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 443, name: '洪湖瞿家湾古建筑群', year: 1800, dynasty: '清', desc: '江汉民居与街巷空间保存较好的水乡聚落', tech: '水乡古镇·街巷民居', category: '民居', impactFactor: 5, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['沿街布局', '院落组合'] } },
    { id: 444, name: '黄梅五祖寺大雄宝殿', year: 1100, dynasty: '宋', desc: '禅宗五祖道场核心殿宇', tech: '禅宗祖庭·宋代殿宇', category: '寺庙', impactFactor: 7, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 445, name: '长沙开福寺', year: 927, dynasty: '五代', desc: '长沙名刹，湖湘佛教建筑代表', tech: '五代古寺·湖湘佛教', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['榫卯', '院落布局'] } },
    { id: 446, name: '岳麓书院讲堂', year: 1167, dynasty: '南宋', desc: '千年学府核心建筑，湖湘文化地标', tech: '书院建筑·讲堂空间', category: '祭祀', impactFactor: 9, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['书院布局', '榫卯'] } },
    { id: 447, name: '衡山南岳大庙正殿', year: 1882, dynasty: '清', desc: '南岳衡山祭祀建筑群核心，礼制规模宏大', tech: '岳庙建筑·礼制中轴', category: '祭祀', impactFactor: 8, features: { structureType: '木构', roofType: '重檐庑殿顶', material: ['木', '砖', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 448, name: '永州柳子庙', year: 1056, dynasty: '北宋', desc: '纪念柳宗元的重要祠庙，文人祠庙代表', tech: '文人祠庙·宋代创建', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['祠堂布局', '榫卯'] } },
    { id: 449, name: '凤凰古城万寿宫', year: 1736, dynasty: '清', desc: '湘西会馆式建筑代表，装饰华丽', tech: '会馆建筑·湘西装饰', category: '宫殿', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖', '石'], constructionTech: ['木雕', '会馆布局'] } },
    { id: 450, name: '芷江天后宫', year: 1767, dynasty: '清', desc: '内河航运背景下形成的妈祖信仰建筑', tech: '妈祖宫庙·航运文化', category: '祭祀', impactFactor: 5, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['榫卯', '会馆式布局'] } },
    { id: 451, name: '洪江古商城窨子屋群', year: 1700, dynasty: '清', desc: '湘西商业建筑与民居结合的传统街区', tech: '窨子屋·商居合一', category: '民居', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['商居合一', '街巷布局'] } },
    { id: 452, name: '郴州苏仙观', year: 1200, dynasty: '宋', desc: '湘南道教建筑遗存，山地景观条件突出', tech: '山地道观·湘南文化', category: '道观', impactFactor: 5, features: { structureType: '木构', roofType: '悬山顶', material: ['木', '石'], constructionTech: ['依山而建', '榫卯'] } },
    { id: 453, name: '张家界普光禅寺', year: 1500, dynasty: '明', desc: '湘西北佛寺代表，山门与殿宇层次明确', tech: '山地寺庙·湘西禅寺', category: '寺庙', impactFactor: 5, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '瓦'], constructionTech: ['依山布局', '榫卯'] } },
    { id: 454, name: '临海江南长城揽胜门', year: 997, dynasty: '北宋', desc: '台州府城城墙核心城门，山海防御体系代表', tech: '城防体系·山地城墙', category: '城防', impactFactor: 7, features: { structureType: '砖石', roofType: '城门楼', material: ['砖', '石', '木'], constructionTech: ['夯土', '包砖', '城门楼'] } },
    { id: 455, name: '宁海前童古镇职思其居', year: 1800, dynasty: '清', desc: '浙东大户民居代表，聚落肌理完整', tech: '浙东民居·宗族聚落', category: '民居', impactFactor: 5, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['宗族聚落', '院落布局'] } },
    { id: 456, name: '兰溪诸葛八卦村大公堂', year: 1700, dynasty: '清', desc: '八卦形聚落中心祠堂建筑，布局独特', tech: '八卦聚落·中心祠堂', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['八卦布局', '祠堂建筑'] } },
    { id: 457, name: '温州江心寺', year: 869, dynasty: '唐', desc: '瓯江江心岛古寺，水域环境鲜明', tech: '江心古寺·水陆景观', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖', '水'], constructionTech: ['榫卯', '园林布局'] } },
    { id: 458, name: '绍兴仓桥直街古建筑群', year: 1600, dynasty: '明', desc: '水乡街巷与民居店铺并存的历史街区', tech: '水乡街区·街宅合一', category: '民居', impactFactor: 5, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖', '水'], constructionTech: ['沿河布局', '街宅结合'] } },
    { id: 459, name: '嘉兴烟雨楼', year: 1518, dynasty: '明', desc: '南湖湖心岛楼阁建筑，江南园林意境突出', tech: '湖心楼阁·借景南湖', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '卷棚顶', material: ['木', '水', '石'], constructionTech: ['借景', '园林布局'] } },
    { id: 460, name: '常熟方塔园方塔', year: 1148, dynasty: '南宋', desc: '江南古塔与园林结合的代表', tech: '方塔·园林整合', category: '塔', impactFactor: 6, features: { structureType: '砖木', roofType: '攒尖顶', material: ['砖', '木'], constructionTech: ['砖仿木', '塔院布局'] } },
    { id: 461, name: '苏州双塔寺遗址', year: 982, dynasty: '北宋', desc: '双塔与寺院遗址组合，古城格局的重要坐标', tech: '双塔格局·寺院遗址', category: '遗址', impactFactor: 7, features: { structureType: '砖石', roofType: '无', material: ['砖', '石'], constructionTech: ['遗址展示', '塔群布局'] } },
    { id: 462, name: '昆山千灯延福寺塔', year: 1160, dynasty: '南宋', desc: '江南古镇砖塔代表，塔街关系清晰', tech: '南宋砖塔·古镇地标', category: '塔', impactFactor: 5, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['砖砌'] } },
    { id: 463, name: '扬州文昌阁', year: 1585, dynasty: '明', desc: '扬州城市地标性楼阁，交通节点鲜明', tech: '城市楼阁·交通枢纽', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '攒尖顶', material: ['木', '砖'], constructionTech: ['楼阁结构', '榫卯'] } },
    { id: 464, name: '镇江金山寺慈寿塔', year: 1068, dynasty: '北宋', desc: '江上寺院古塔，山水佛寺组合典型', tech: '江上古寺·塔院结合', category: '塔', impactFactor: 6, features: { structureType: '砖木', roofType: '攒尖顶', material: ['砖', '木'], constructionTech: ['砖仿木', '山地布局'] } },
    { id: 465, name: '无锡惠山寄畅园知鱼槛', year: 1527, dynasty: '明', desc: '寄畅园景观建筑之一，江南园林空间精巧', tech: '园林亭榭·借景山水', category: '园林', impactFactor: 5, features: { structureType: '木构', roofType: '卷棚顶', material: ['木', '石', '水'], constructionTech: ['借景', '框景'] } },
    { id: 466, name: '南通狼山广教寺', year: 958, dynasty: '五代', desc: '沿江山地寺院，城市景观地标', tech: '山地寺庙·沿江景观', category: '寺庙', impactFactor: 5, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '石'], constructionTech: ['依山而建', '榫卯'] } },
    { id: 467, name: '北京天宁寺塔', year: 1120, dynasty: '辽', desc: '辽代密檐砖塔，燕京古塔代表', tech: '辽代砖塔·密檐形制', category: '塔', impactFactor: 8, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['密檐塔', '砖砌'] } },
    { id: 468, name: '北京妙应寺白塔', year: 1271, dynasty: '元', desc: '元代覆钵式白塔，北京城重要地标', tech: '覆钵式塔·元代佛塔', category: '塔', impactFactor: 8, features: { structureType: '砖石', roofType: '覆钵顶', material: ['砖', '石'], constructionTech: ['藏式塔', '砖石结构'] } },
    { id: 469, name: '北京智化寺万佛阁', year: 1444, dynasty: '明', desc: '明代寺院木构精品，京音乐文化著名', tech: '明代木构·佛阁建筑', category: '寺庙', impactFactor: 7, features: { structureType: '木构', roofType: '歇山顶', material: ['木'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 470, name: '北京正觉寺五塔', year: 1473, dynasty: '明', desc: '金刚宝座塔代表，北京真觉寺标志', tech: '金刚宝座塔·藏式影响', category: '塔', impactFactor: 7, features: { structureType: '砖石', roofType: '塔式组合', material: ['砖', '石'], constructionTech: ['石雕', '塔式组合'] } },
    { id: 471, name: '北京先农坛太岁殿', year: 1420, dynasty: '明', desc: '皇家祭农建筑群中的重要殿宇', tech: '坛庙建筑·皇家礼制', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['中轴布局', '榫卯'] } },
    { id: 472, name: '天津蓟州白塔', year: 1058, dynasty: '辽', desc: '辽代砖塔，蓟州古城重要标识', tech: '辽代古塔·砖塔遗存', category: '塔', impactFactor: 6, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['砖砌'] } },
    { id: 473, name: '天津广东会馆戏楼', year: 1907, dynasty: '清', desc: '近代会馆戏楼建筑代表，南北风格兼具', tech: '会馆戏楼·近代营造', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['戏楼结构', '会馆布局'] } },
    { id: 474, name: '大同九龙壁', year: 1392, dynasty: '明', desc: '现存规模最大的琉璃九龙壁之一', tech: '琉璃影壁·皇家装饰', category: '宫殿', impactFactor: 7, features: { structureType: '砖石', roofType: '无', material: ['琉璃砖', '砖'], constructionTech: ['琉璃烧造', '影壁构筑'] } },
    { id: 475, name: '浑源永安寺传法正宗殿', year: 1318, dynasty: '元', desc: '元代木构与壁画并重的珍贵寺院建筑', tech: '元代木构·壁画遗存', category: '寺庙', impactFactor: 8, features: { structureType: '木构', roofType: '歇山顶', material: ['木'], constructionTech: ['榫卯', '壁画'] } },
    { id: 476, name: '朔州应县净土寺藻井', year: 1124, dynasty: '金', desc: '净土寺殿内藻井木作艺术精绝', tech: '金代木作·藻井艺术', category: '寺庙', impactFactor: 7, features: { structureType: '木构', roofType: '歇山顶', material: ['木'], constructionTech: ['藻井', '榫卯'] } },
    { id: 477, name: '高平游仙寺', year: 929, dynasty: '五代', desc: '五代寺庙遗存，地方木构价值较高', tech: '五代木构·地方寺院', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '悬山顶', material: ['木'], constructionTech: ['榫卯'] } },
    { id: 478, name: '太谷曹家大院', year: 1700, dynasty: '清', desc: '晋商宅院代表，民居与商业功能结合', tech: '晋商大院·商宅合一', category: '民居', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['院落布局', '砖雕'] } },
    { id: 479, name: '祁县渠家大院', year: 1760, dynasty: '清', desc: '晋商宅院群之一，空间尺度宏大', tech: '晋商宅院·雕刻装饰', category: '民居', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖', '石'], constructionTech: ['院落布局', '木雕'] } },
    { id: 480, name: '临汾东岳庙', year: 1300, dynasty: '元', desc: '地方岳庙建筑遗存，礼制格局清晰', tech: '岳庙建筑·元代遗存', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['院落布局', '榫卯'] } },
    { id: 481, name: '西安兴教寺玄奘塔', year: 669, dynasty: '唐', desc: '玄奘法师安葬塔，唐代佛教遗存重要节点', tech: '唐代砖塔·玄奘纪念', category: '塔', impactFactor: 8, features: { structureType: '砖石', roofType: '攒尖顶', material: ['砖'], constructionTech: ['砖砌', '塔式结构'] } },
    { id: 482, name: '西安卧龙寺', year: 710, dynasty: '唐', desc: '长安古寺之一，佛寺布局延续性强', tech: '唐代古寺·长安佛教', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['榫卯', '院落布局'] } },
    { id: 483, name: '耀州药王山石刻', year: 618, dynasty: '唐', desc: '摩崖造像与碑刻并存的医药文化遗存', tech: '摩崖石刻·医药文化', category: '石窟', impactFactor: 6, features: { structureType: '石构', roofType: '无', material: ['石'], constructionTech: ['石刻', '摩崖'] } },
    { id: 484, name: '韩城城隍庙', year: 1455, dynasty: '明', desc: '韩城古城礼制建筑代表，戏台与庙宇并存', tech: '明代城隍庙·戏台组合', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['戏台结构', '榫卯'] } },
    { id: 485, name: '合阳福山景区古建群', year: 1500, dynasty: '明', desc: '关中地区山地祭祀建筑群，层级丰富', tech: '山地祭祀·古建群', category: '祭祀', impactFactor: 5, features: { structureType: '木构', roofType: '悬山顶', material: ['木', '石'], constructionTech: ['依山而建', '院落组合'] } },
    { id: 486, name: '临潼华清宫遗址', year: 747, dynasty: '唐', desc: '唐代离宫遗址，皇家园林与温泉建筑并重', tech: '皇家离宫·温泉建筑', category: '遗址', impactFactor: 8, features: { structureType: '土木', roofType: '无', material: ['砖', '石', '土'], constructionTech: ['宫苑规划', '遗址展示'] } },
    { id: 487, name: '洛阳丽景门城楼', year: 1217, dynasty: '金', desc: '古城门楼，延续洛阳城市轴线记忆', tech: '城门楼·古都门户', category: '城防', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['城楼结构', '砖砌'] } },
    { id: 488, name: '安阳岳飞庙', year: 1450, dynasty: '明', desc: '纪念岳飞的重要祠庙建筑', tech: '忠烈祠庙·纪念建筑', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '硬山顶', material: ['木', '砖'], constructionTech: ['祠堂布局', '榫卯'] } },
    { id: 489, name: '郑州城隍庙', year: 1368, dynasty: '明', desc: '中原城市宗教建筑与商业空间结合的代表', tech: '城隍庙·市井空间', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '歇山顶', material: ['木', '砖'], constructionTech: ['院落布局', '榫卯'] } },
    { id: 490, name: '新乡潞王陵神道石刻', year: 1578, dynasty: '明', desc: '明代藩王陵寝石刻遗存，礼制意味浓厚', tech: '王陵石刻·礼制空间', category: '祭祀', impactFactor: 6, features: { structureType: '石构', roofType: '无', material: ['石'], constructionTech: ['石刻', '神道布局'] } },
    { id: 491, name: '曲阜颜庙复圣殿', year: 1442, dynasty: '明', desc: '祭祀颜回的重要殿堂，孔孟文化建筑群组成部分', tech: '儒家祠庙·复圣殿', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 492, name: '济宁太白楼', year: 1388, dynasty: '明', desc: '纪念李白的名楼，运河文化地标', tech: '纪念楼阁·运河地标', category: '楼阁', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['楼阁结构', '榫卯'] } },
    { id: 493, name: '青州真教寺', year: 1292, dynasty: '元', desc: '元代伊斯兰建筑遗存，地方文化交汇代表', tech: '伊斯兰建筑·元代遗存', category: '寺庙', impactFactor: 6, features: { structureType: '砖石', roofType: '穹顶', material: ['砖', '石'], constructionTech: ['拱券', '伊斯兰风格'] } },
    { id: 494, name: '曲阜周公庙元圣殿', year: 1119, dynasty: '北宋', desc: '祭祀周公的古建筑群核心殿宇', tech: '宋代礼制殿宇·周公庙', category: '祭祀', impactFactor: 7, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['榫卯', '斗拱'] } },
    { id: 495, name: '泰安王母池古建筑群', year: 1545, dynasty: '明', desc: '泰山脚下道教建筑群，山岳祭祀体系的一部分', tech: '山岳道观·泰山信仰', category: '道观', impactFactor: 5, features: { structureType: '木构', roofType: '悬山顶', material: ['木', '石'], constructionTech: ['依山布局', '榫卯'] } },
    { id: 496, name: '福州鼓山涌泉寺大雄宝殿', year: 908, dynasty: '后梁', desc: '闽都名寺核心建筑，山林佛寺空间典型', tech: '山林佛寺·大雄宝殿', category: '寺庙', impactFactor: 6, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '瓦'], constructionTech: ['依山而建', '榫卯'] } },
    { id: 497, name: '泉州六胜塔', year: 1128, dynasty: '北宋', desc: '海上丝路航标塔代表，临海而立', tech: '航标古塔·海丝遗存', category: '塔', impactFactor: 7, features: { structureType: '石构', roofType: '攒尖顶', material: ['石'], constructionTech: ['石塔', '航标功能'] } },
    { id: 498, name: '南平和平古镇谯楼', year: 1450, dynasty: '明', desc: '闽北古镇公共楼阁建筑，街巷节点鲜明', tech: '古镇谯楼·公共空间', category: '楼阁', impactFactor: 5, features: { structureType: '木构', roofType: '重檐歇山顶', material: ['木', '砖'], constructionTech: ['楼阁结构', '街巷节点'] } },
    { id: 499, name: '漳州东山关帝庙', year: 1387, dynasty: '明', desc: '闽南关帝信仰建筑代表，装饰与礼制并重', tech: '关帝庙·闽南装饰', category: '祭祀', impactFactor: 6, features: { structureType: '木构', roofType: '燕尾脊', material: ['木', '砖', '石'], constructionTech: ['榫卯', '闽南木作', '石雕'] } },`;

const marker = `    {id:399,name:'江油云岩寺飞天藏',year:960,dynasty:'北宋',desc:'旋转藏经阁遗存，木作结构独特',tech:'宋代木作·转轮藏',category:'寺庙',impactFactor:7,features:{structureType:'木构',roofType:'攒尖顶',material:['木'],constructionTech:['榫卯','转轮结构']}},\n  ];`;

if (!content.includes(marker)) {
  throw new Error('Marker for inserting 400-499 not found.');
}

content = content.replace(marker, `${marker.slice(0, -4)}\n${moreBuildings}\n  ];`);
content = content.replace('  // 当前已汇总真实古建筑数据至500条', '  // 当前已汇总真实古建筑数据至500条');

fs.writeFileSync(filePath, content, 'utf8');
console.log('Inserted extendedBuildings 400-499 successfully.');
